Endpoints for evaluation route added
ComputerSocietyVITC/Lemons pull request #27
Opened 2024-12-29 10:37 UTC by AltSumpreme

# Evaluation API Endpoints

## **PUT /evaluations**
**Description:**  
Create a new evaluation.

**Request Body:**
```json
{
  "projectId": "string",
  "score": "number"
}
```

**Authorized Roles:**  
- SUPERADMIN  
- EVALUATOR  

---

## **GET /evaluations**
**Description:**  
Retrieve all evaluations.

**Authorized Roles:**  
- SUPERADMIN  
- EVALUATOR  
- ADMIN  
- USER (only the projects they have created)  

---

## **GET /evaluations/:id**
**Description:**  
Retrieve a specific evaluation by ID.

**Authorized Roles:**  
- SUPERADMIN  
- EVALUATOR  
- ADMIN  

---

## **DELETE /evaluations/:id**
**Description:**  
Delete an evaluation.

**Authorized Roles:**  
- SUPERADMIN  
- EVALUATOR  

## Bearer Authentication added to swagger documentation

![image](https://github.com/user-attachments/assets/f407d312-bf7d-4603-8092-c973edeae41d)

2024-12-29 11:49 UTC, Aditya-Jyoti requested changes
remove redundant code

2024-12-29 11:49 UTC, Aditya-Jyoti commented on src/routes/evalutation/index.ts
> +evaluationRouter.use("*", middleware);
middleware is only set in `src/index.ts` no need for explicit declaration here

2024-12-29 11:49 UTC, Aditya-Jyoti commented on src/routes/evalutation/index.ts
> +    const allowedRoles: Role[] = ["SUPER_ADMIN", "EVALUATOR"];
check for role access before getting data, ie this line should go before `const {projectId, score}...`

2024-12-29 11:49 UTC, Aditya-Jyoti commented on src/routes/evalutation/index.ts
> +}
why are hono and jwtPayload being used here? looks redundant

2024-12-29 11:49 UTC, Aditya-Jyoti commented on src/routes/evalutation/index.ts
> +import { middleware } from "../../lib/auth-provider.js";
no middleware import here

2024-12-29 11:49 UTC, Aditya-Jyoti commented on src/routes/evalutation/index.ts
> +evaluationRouter.openapi(getEvaluation, async (ctx) => {
make this a simple fetch all endpoint restricted to user and admin, remove redundant logic

2024-12-29 11:49 UTC, Aditya-Jyoti commented on src/routes/evalutation/index.ts
> +evaluationRouter.openapi(getEvaluationById, async (ctx) => {
let this be the endpoint that allows users to see their evaluation, unlock this to everyone

2024-12-29 11:49 UTC, Aditya-Jyoti commented on src/lib/auth-provider.ts
> +    const decoded = (await verify(authHeader, process.env.JWT_SECRET)) as {
was this giving a type error?

2024-12-29 11:49 UTC, Aditya-Jyoti commented on src/routes/evalutation/route.ts
> +            projectId: z.string().uuid(),
give examples here too

2024-12-29 11:49 UTC, Aditya-Jyoti commented on src/routes/evalutation/route.ts
> +              id: z.string().uuid(),
missing examples

2024-12-29 11:49 UTC, Aditya-Jyoti commented on package.json
> +    "jsonwebtoken": "^9.0.2",
use native "hono/jwt" whenever working with jwt related logic

2024-12-29 11:49 UTC, Aditya-Jyoti commented on src/index.ts
> +app.route("/evaluation", evaluationRouter);
evaluation route does not get defined here, it gets defined at the very end after middleware has been declared

2024-12-29 11:49 UTC, Aditya-Jyoti commented on src/index.ts
> +  security: [{ Bearer: [] }],
no need for this

2024-12-29 13:56 UTC, AltSumpreme commented on src/lib/auth-provider.ts
> +    const decoded = (await verify(authHeader, process.env.JWT_SECRET)) as {
yup

2024-12-29 14:34 UTC, AltSumpreme commented on src/routes/evalutation/index.ts
> +}
i was getting a type error for the user hence i had to call in interface JWTPayload for the same.

2024-12-30 08:36 UTC, Aditya-Jyoti requested changes

2024-12-30 08:36 UTC, Aditya-Jyoti commented on src/routes/evalutation/index.ts
> +interface JWTPayload {
remove this

2024-12-30 08:36 UTC, Aditya-Jyoti commented on src/routes/evalutation/index.ts
> +    const user = ctx.get("user");
replace with `const user = getCurrentUser(ctx);` from `auth-provider` it will fix the jwt type error.

2024-12-30 08:36 UTC, Aditya-Jyoti commented on src/routes/evalutation/route.ts
> +          schema: z.object({
evaluation schema exists in `/schemas` use them for more consistent typing

2024-12-30 08:36 UTC, Aditya-Jyoti commented on src/routes/evalutation/index.ts
> +  const id = ctx.req.param("id");
retrieve id _after_ you have checked for valid roles

2024-12-30 08:36 UTC, Aditya-Jyoti commented on src/routes/evalutation/route.ts
> +          example: [
dont do it like this, use the `.openapi({example: })` method, this leads to inconsistencies

2024-12-30 08:36 UTC, Aditya-Jyoti commented on src/routes/evalutation/route.ts
> +          example: {
same dont do this, also use the schemas defined in `/schemas` as best as you can

2024-12-30 14:12 UTC, Shashwatm74 commented on src/routes/evalutation/index.ts
> +    if (score < 0 || score > 10) {
make the highest score variable

2024-12-30 14:12 UTC, Shashwatm74 commented on src/routes/evalutation/index.ts
> +evaluationRouter.openapi(getEvaluationById, async (ctx) => {
too much redundant logic can be written in a better way...

2024-12-30 14:12 UTC, Shashwatm74 commented on src/routes/evalutation/index.ts
> +evaluationRouter.openapi(deleteEvaluation, async (ctx) => {
deleting the evaluation directly without checking if it exists

2024-12-30 14:12 UTC, Shashwatm74 commented on src/routes/evalutation/index.ts
> +evaluationRouter.openapi(getEvaluation, async (ctx) => {
give perm to admin too

2024-12-30 14:12 UTC, Shashwatm74 commented on src/routes/evalutation/index.ts
> +evaluationRouter.openapi(deleteEvaluation, async (ctx) => {
give perm to admin too

2024-12-30 14:12 UTC, Shashwatm74 commented on src/routes/evalutation/route.ts
> +            score: z.number().min(0).max(10).openapi({
higher score variable

2024-12-30 14:12 UTC, Shashwatm74 commented on src/lib/auth-provider.ts
> +      exp: number;
handle expired tokrns

2024-12-30 15:24 UTC, Shashwatm74 requested changes

2024-12-30 15:24 UTC, Shashwatm74 commented on src/routes/evalutation/index.ts
> +    if (score < 0) {
have a higher score check but with a variable istead of a hard value

2024-12-30 15:24 UTC, Shashwatm74 commented on src/routes/evalutation/index.ts
>  evaluationRouter.openapi(getEvaluationById, async (ctx) => {
logic can be simplified further

2024-12-30 15:24 UTC, Shashwatm74 commented on src/routes/evalutation/index.ts
>      await prisma.evaluation.updateMany({
send back the updated record with the message record updated

2024-12-30 15:24 UTC, Shashwatm74 commented on src/routes/evalutation/route.ts
> +              description: "Score for the evaluation, must be greater than 0",
add variable highest score

2025-01-02 06:03 UTC, Aditya-Jyoti approved these changes

2025-01-02 06:24 UTC, Shashwatm74 approved these changes
LGTM!!

2025-01-03 03:27 UTC, merged