feat: added endpoint for teams
ComputerSocietyVITC/Lemons pull request #28
Opened 2024-12-30 09:00 UTC by TheChilledBuffalo

Issue #15 , with changes as described below.

## **POST /teams**
**Description**
Create a new team

**Request Body:**
```json
{
  "name": "string",
  "imageId": "string"
}
```

**Authorized Roles**
- SUPERADMIN
- ADMIN
- USER (if Leader)

---

## **GET /teams**
**Description**
Retrieve all teams

**Authorized Roles**
- SUPERADMIN
- ADMIN
- EVALUATOR

---

##**GET /teams/:id**
**Description**
Retrieve a specific team by ID

**Authorized Roles**
- SUPERADMIN
- ADMIN
- EVALUATOR
- USER (only their own team)

---

##**DELETE /teams/:id**
**Description**
Remove a team

**Authorized Roles**
- SUPERADMIN

2024-12-30 14:26 UTC, Shashwatm74 requested changes

2024-12-30 14:26 UTC, Shashwatm74 commented on src/routes/teams/index.ts
> +    if (!teams) {
teams.length === 0 use this as findMany will give a empty array if no teams registered

2024-12-30 14:26 UTC, Shashwatm74 commented on src/routes/teams/index.ts
> +    if (checkRole([Role.USER], ctx)) {
Better to have the roles that are allowed as if we expand the roles

2024-12-30 14:26 UTC, Shashwatm74 commented on src/routes/teams/index.ts
> +    const team = await prisma.team.findUnique({
add roles for the same reason as above

2024-12-30 14:44 UTC, ThEditor requested changes

2024-12-30 14:44 UTC, ThEditor commented on src/routes/teams/routes.ts
> +              team: TeamSchema,
Are you sure the data you actually send follows the defined schema?
Ensure that the returned json is like:
```
{
  data: [{}, {}, {}, ...]
}
```
where {} are teams

2024-12-30 14:44 UTC, ThEditor commented on src/routes/teams/routes.ts
> +    200: {
Also respond with created team data

2024-12-30 14:46 UTC, Shashwatm74 requested changes

2024-12-30 14:46 UTC, Shashwatm74 commented on src/routes/teams/routes.ts
Add examples as well for neat documentation

2025-01-02 06:18 UTC, ThEditor requested changes, later dismissed
Last one ^.^

2025-01-02 06:18 UTC, ThEditor commented on src/routes/teams/routes.ts
> +                team: TeamSchema,
i was thinking more like
```
schema: z.object({
  data: z.array(TeamSchema)
})
```
(ps: correct me if I'm wrong here)

2025-01-02 06:25 UTC, Shashwatm74 approved these changes
LGTM!!

2025-01-03 03:28 UTC, Aditya-Jyoti commented on src/routes/teams/routes.ts
> +                team: TeamSchema,
TeamSchema itself is a zod object so no need for explicit formatting

2025-01-03 05:51 UTC, TheChilledBuffalo commented on src/routes/teams/routes.ts
> +                team: TeamSchema,
So no changes to be made here?

2025-01-03 05:51 UTC, TheChilledBuffalo commented
@Aditya-Jyoti conflicts resolved, ready for merging

2025-01-05 11:32 UTC, merged